### ISSUE TITLE
Ultraslow consensus on one of the packages on chimp dataset

### ISSUE THREAD

**Issue by Dmitry-Antipov** [marbl/verkko#166] opened 2023-07-03 14:53 UTC
It took 5 days to finish a consensus task, seems that most time was spent on lots of short contigs with few reads
  /data/antipovd2/res/primates/chimp/test_patch2/8-hicPipeline/final_contigs/7-consensus/packages/part007.err

**Comment by skoren** [comment] 2023-07-03 21:11
Should be fixed by commit #3a48318, re-running consensus now to confirm.

**Comment by skoren** [comment] 2023-07-04 13:39
Confirmed, with the fix the same partition finished in 14 hrs.

**Closed by skoren** 2023-07-04 13:39 UTC

**Comment by hzhang-2021** [comment] 2026-02-13 06:45
i met the same problem, and i found the following message at  8-hicPipeline/run_mashmap.err
---Running MashMap
/usr/local/genome/miniforge3/envs/t2t/bin/mashmap: error while loading shared libraries: libblis.so.4: cannot open shared object file: No such file or directory

Then I add the libblis.so.4 with following steps at my rocky8 server.
# dnf install -y blis blis-devel
# ln -s /usr/lib64/libblis.so /usr/lib64/libblis.so.4

then i start the analysis , hope this will complete....

**Comment by skoren** [comment] 2026-02-13 14:09
@hzhang-2021 I think you were thinking of the mentioned issue #162 not this one with consensus. That is issue with conda installation of mashmap: https://github.com/marbl/MashMap/issues/72. Adding the missing lib should make it work. However, I suspect this means your verkko and mashmap installation are not the latest releases since that issue was resolved by subsequent mashmap releases.
