### ISSUE TITLE
Long running ComputeOverlaps on Revio data

### ISSUE THREAD

**Issue by wharvey31** [marbl/verkko#117] opened 2022-11-28 18:30 UTC
Hello,

We are running verkko v1.2 (bioconda) on the newly released HG002 revio set. We are experiencing incredibly long (>7 days) runtime on some computeOverlaps jobs. The jobs seem to be running with the appropriate number of threads, but just takes a long time to complete.

The input files are about 15G and are available here: https://eichlerlab.gs.washington.edu/public/wharvey/verkko/revio-out.tgz as specified from: 

```
rule computeOverlaps:
    input: 0-correction/hifi.seqStore, 0-correction/hifi.ignoremers, 0-correction/overlap-jobs/000424.params, 0-correction/configureOverlaps.finished
```

If that is too difficult to access, we can set up a Globus link as well. Thanks and let me know if you need anymore info!

**Comment by brianwalenz** [comment] 2022-11-28 19:37
@skoren experienced a similar fate with these reads.  It's caused by the kmer seeds-to-ignore (`0-correction/hifi.ignoremers`) missing some high-copy kmers; *why* they're missing is unknown.  We haven't implemented a fix yet.

Theory of Operation:  Meryl counts kmers in 4x 1/100th of the reads, merges those results and outputs any kmer that occurs 20 times or more.  These kmers are excluded from seeding an overlap since they are too common to reliably find unique overlaps.  This sampling scheme worked well for development; it is very fast, but it is a horrible hack.

Fix:  Make it count more data.  In `0-correction/countKmers.sh`, change the four instances of `segment=n/100`  (1/100, 33/100, 66/100 and 99/100) to something like 1/20, 7/20, 13/20, 20/20 and increase `greater-than 20` to `greater-than 100`.  This will count kmers in 20% of the input data instead of just 4%.  Run the script on a node with 4 CPUs and 32-64 GB memory.

The same fix could be applied to verkko in `src/Snakefiles/c2-countKmers.sm`; it's just patching a hack though, and I'd rather fix it properly before committing to verkko....but there are some technical challenges involved.

**Comment by wharvey31** [comment] 2022-11-28 20:07
Thanks for the reply Brian. Looking forward to a solution!

**Comment by skoren** [comment] 2022-11-29 02:06
Yep, what @brianwalenz said is a good workaround until there's a permanent fix. I counted all k-mers instead in these datasets (changing the 1/100 to be 1/20, 2/20, ... 20/20) and set threshold to 10*coverage so for 30-fold (assuming 3gb size), set it to 300. 

I think we should just count all the k-mers all the time in verkko, it's not a big computational bottleneck and will avoid issues like this in the future.

**Comment by skoren** [comment] 2023-02-13 17:48
This should be integrated in the latest code in the repo and will be in the next release.

**Closed by skoren** 2023-02-13 17:48 UTC
