### ISSUE TITLE
Error of processONT.sh

### ISSUE THREAD

**Issue by YouxinZhao** [marbl/verkko#231] opened 2024-02-22 12:28 UTC
I used Verkko2.0 to assemble the genome, but it stopped when run processONT.sh（step16）

processONT.err
![image](https://github.com/marbl/verkko/assets/95477328/bdf7d623-089c-4d88-9167-93c899482991)

ont_resolved_graph.gfa.err
![image](https://github.com/marbl/verkko/assets/95477328/69e3d820-89ef-46d3-91c1-21dfc4f54687)

It should be point, that i did not find fake-ont-paths.txt

**Comment by skoren** [comment] 2024-02-22 15:14
This looks like the intended behavior due to the graph having a rare and not resolvable structure. @maickrau do you have a suggested workaround? @YouxinZhao can you share the 4-processONT folder (https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you)?

**Comment by YouxinZhao** [comment] 2024-02-23 01:29
Thank you very much. I have sent the file with ftp（4-processONT.tar.gz).
The genome I assembled （20X Hifi, trio , 15X Ont) was extremely rich in simple repeats, with a genome size of 2.6g.  However the hifi-resolved.gfa was only 623M.

**Comment by maickrau** [comment] 2024-02-26 08:20
Commit [36fb021](https://github.com/marbl/verkko/commit/36fb021c565778b1f59e1ee166e597012d488f4f) prevents the crash and instead just leaves the case unresolved. I think the case is probably just a spurious node so leaving it unresolved shouldn't be a problem.

**Comment by skoren** [comment] 2024-03-01 18:44
Should be fixed by the commit, confirmed as fixed by #233

**Closed by skoren** 2024-03-01 18:44 UTC
