### ISSUE TITLE
error in "ont_resolved_graph.gfa.err"

### ISSUE THREAD

**Issue by socialhang** [marbl/verkko#227] opened 2024-01-25 01:17 UTC
resolve with edge support 20
resolve hairpin >utig1-140
resolve k=3316, extended 1 nodes into 2 nodes
resolve k=7068, extended 1 nodes into 2 nodes
resolve k=19076, extended 1 nodes into 2 nodes
resolve k=27406, extended 1 nodes into 2 nodes
resolve with edge support 10
resolve k=40079, extended 1 nodes into 2 nodes
resolve k=79997, extended 1 nodes into 2 nodes
resolve with edge support 5
resolve k=11727, extended 1 nodes into 2 nodes
done resolving
write paths
Traceback (most recent call last):
  File "/work/home/acg43aksd4/yingpan1/01.data/pipline/verkko/lib/verkko/scripts/resolve_triplets_kmerify.py", line 1056, in <module>
    f.write("".join(n[0] + unitig_name[n[1:]] for n in path) + "\n")
  File "/work/home/acg43aksd4/yingpan1/01.data/pipline/verkko/lib/verkko/scripts/resolve_triplets_kmerify.py", line 1056, in <genexpr>
    f.write("".join(n[0] + unitig_name[n[1:]] for n in path) + "\n")
KeyError: 'utig1-140'

**Comment by skoren** [comment] 2024-01-25 04:47
There have been some fixes to this code after the last release so this might be fixed. Are you able to share your 1-buildGraph, 2-processGraph, and 4-processONT folders to our FTP. The info on uploading is here: https://canu.readthedocs.io/en/latest/faq.html#how-can-i-send-data-to-you

**Comment by socialhang** [comment] 2024-01-25 05:49
Thanks！

I will try the new version of verkko firstly! Can this version of verkko be installed through conda?

**Comment by skoren** [comment] 2024-02-11 15:32
The release is available both on the site here to compile and on conda so please test on your data to see if the issue is fixed

**Comment by skoren** [comment] 2024-03-04 21:38
Idle, hopefully addressed by the updated release

**Closed by skoren** 2024-03-04 21:38 UTC
